---
  # Site24x7 OracleTablespaceUsage Python File Setup
   - name: "Site24x7 OracleTablespaceUsage Python File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceUsage/OracleTablespaceUsage.py"
     register: OracleTablespaceUsage_python_file_check

   - name: "Extracting Python3 Default Path."
     command: which python3
     register: python3_path

   - set_fact:
      actual_path: "{{ '#!'+python3_path.stdout }}"

   - name: "Setting the Default Python Path for the Site24x7 OracleTablespaceUsage Plugin"
     lineinfile:
       path: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceUsage/OracleTablespaceUsage.py"
       regexp: "#!"
       line: "{{actual_path}}"
     when: OracleTablespaceUsage_python_file_check.stat.exists

   - name: "Checking the Site24x7 OracleTablespaceUsage Plugin Output"
     shell: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceUsage/OracleTablespaceUsage.py --hostname={{Oracle_host}} --port={{Oracle_port}} --username={{Oracle_username}} --password={{Oracle_password}} --tablespace_names={{Oracle_tablespace_names}} --oracle_home={{Oracle_home}} --sid={{Oracle_sid}} --tls={{Oracle_tls}} --wallet_location={{Oracle_wallet_location}}"
     register: OracleTablespaceUsage_python_output
     when: OracleTablespaceUsage_python_file_check.stat.exists

   - name: "Site24x7 OracleTablespaceUsage plugins with Error !"
     debug:
      msg: "Site24x7 OracleTablespaceUsage Plugin OUTPUT error ! \n {{ OracleTablespaceUsage_python_output.stdout }}"
     when: "'\"status\": 0' in OracleTablespaceUsage_python_output.stdout and OracleTablespaceUsage_python_file_check.stat.exists"

   - name: "Moving the Site24x7 OracleTablespaceUsage Folder to the Plugins Directory"
     command: "mv  /opt/site24x7/monagent/temp/plugins/OracleTablespaceUsage /opt/site24x7/monagent/plugins"
     ignore_errors: true
     when: "plugin_path_check.stat.exists and '\"status\": 0' not in OracleTablespaceUsage_python_output.stdout"

     