---

   - name: "Site24x7 Temp OracleTablespaceDetails Plugins Directory Creation."
     file:
      path: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails"
      state: directory
     when: agent_path_check.stat.exists

   - name: "Site24x7 Plugin Directory Check"
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails"
     register: plugin_path_check

   - name: "Download the Site24x7 OracleTablespaceDetails Plugin Files."
     get_url:
        url: "{{ item }}"
        dest: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails"
        mode: 0744
     loop: 
      - "https://raw.githubusercontent.com/site24x7/plugins/suraj/OracleFullStackMonitoring/OracleTablespaceDetails/OracleTablespaceDetails.py"
      - "https://raw.githubusercontent.com/site24x7/plugins/suraj/OracleFullStackMonitoring/OracleTablespaceDetails/OracleTablespaceDetails.cfg"
     when: plugin_path_check.stat.exists





     