---
  # Site24x7 OracleTablespaceDetails Plugin Config File Setup
   - name: "Site24x7 OracleTablespaceDetails Config File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails/OracleTablespaceDetails.cfg"
     register: OracleTablespaceDetails_config_file_check

   - name: "Site24x7 OracleTablespaceDetails configuration."
     lineinfile: 
       path: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails/OracleTablespaceDetails.cfg"
       regexp: "{{ item.regex }}"
       line: "{{ item.line }}"
     loop:
       - { regex: 'hostname =', line: 'hostname ={{Oracle_host}}' }
       - { regex: 'port =', line: 'port ={{Oracle_port}}' }
       - { regex: 'username =', line: 'username ={{Oracle_username}}' }
       - { regex: 'password =', line: 'password ={{Oracle_password}}' }
       - { regex: 'tablespace_name =', line: 'tablespace_name ={{Oracle_tablespace_name}}' }
       - { regex: 'oracle_home =', line: 'oracle_home ={{Oracle_home}}' }
       - { regex: 'sid =', line: 'sid ={{Oracle_sid}}' }
       - { regex: 'tls =', line: 'tls ={{Oracle_tls}}' }
       - { regex: 'wallet_location =', line: 'wallet_location ={{Oracle_wallet_location}}' }
     when: OracleTablespaceDetails_config_file_check.stat.exists