---
  # Site24x7 OracleTablespaceDetails Python File Setup
   - name: "Site24x7 OracleTablespaceDetails Python File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails/OracleTablespaceDetails.py"
     register: OracleTablespaceDetails_python_file_check

   - name: "Extracting Python3 Default Path."
     command: which python3
     register: python3_path

   - set_fact:
      actual_path: "{{ '#!'+python3_path.stdout }}"

   - name: "Setting the Default Python Path for the Site24x7 OracleTablespaceDetails Plugin"
     lineinfile:
       path: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails/OracleTablespaceDetails.py"
       regexp: "#!"
       line: "{{actual_path}}"
     when: OracleTablespaceDetails_python_file_check.stat.exists

   - name: "Checking the Site24x7 OracleTablespaceDetails Plugin Output"
     shell: "/opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails/OracleTablespaceDetails.py --hostname={{Oracle_host}} --port={{Oracle_port}} --username={{Oracle_username}} --password={{Oracle_password}} --tablespace_name ={{Oracle_tablespace_name}} --oracle_home={{Oracle_home}} --sid={{Oracle_sid}} --tls={{Oracle_tls}} --wallet_location={{Oracle_wallet_location}}"
     register: OracleTablespaceDetails_python_output
     when: OracleTablespaceDetails_python_file_check.stat.exists

   - name: "Site24x7 OracleTablespaceDetails plugins with Error !"
     debug:
      msg: "Site24x7 OracleTablespaceDetails Plugin OUTPUT error ! \n {{ OracleTablespaceDetails_python_output.stdout }}"
     when: "'\"status\": 0' in OracleTablespaceDetails_python_output.stdout and OracleTablespaceDetails_python_file_check.stat.exists"

   - name: "Moving the Site24x7 OracleTablespaceDetails Folder to the Plugins Directory"
     command: "mv  /opt/site24x7/monagent/temp/plugins/OracleTablespaceDetails /opt/site24x7/monagent/plugins"
     ignore_errors: true
     when: "plugin_path_check.stat.exists and '\"status\": 0' not in OracleTablespaceDetails_python_output.stdout"

     