---

   - name: "Site24x7 Temp OracleWaits Plugins Directory Creation."
     file:
      path: "/opt/site24x7/monagent/temp/plugins/OracleWaits"
      state: directory
     when: agent_path_check.stat.exists

   - name: "Site24x7 Plugin Directory Check"
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/OracleWaits"
     register: plugin_path_check

   - name: "Download the Site24x7 OracleWaits Plugin Files."
     get_url:
        url: "{{ item }}"
        dest: "/opt/site24x7/monagent/temp/plugins/OracleWaits"
        mode: 0744
     loop: 
      - "https://raw.githubusercontent.com/site24x7/plugins/suraj/OracleFullStackMonitoring/OracleWaits/OracleWaits.py"
      - "https://raw.githubusercontent.com/site24x7/plugins/suraj/OracleFullStackMonitoring/OracleWaits/OracleWaits.cfg"
     when: plugin_path_check.stat.exists



     