---
 - name: "Site24x7 <plugin_name> Plugin Installation"
   hosts: all 
   become: yes
   vars:
      <plugin_name>_host: "<plugin_name>_host"
      <plugin_name>_port: "<plugin_name>_port"
      <plugin_name>_username: "<plugin_name>_username"                           
      <plugin_name>_password: "<plugin_name>_password"                             


  
   tasks:    
  # Site24x7 <plugin_name> Prerequisites Check

   - name: "Python3 Installation Check."
     command: "python3 --version"
     register: python_version_output
     ignore_errors: yes

   - name: "Installing Python if not found (for Debian/Ubuntu)."
     apt:
        name: python3
        state: present
     when: "not python_version_output.stdout and ansible_facts['os_family'] == 'Debian'"

   - name: "Installing Python if not found (for CentOS/RedHat)."
     yum:
        name: python3
        state: present
     when: "not python_version_output.stdout and ansible_facts['os_family'] == 'RedHat'"

   - name: "pip3 Installation Check."
     command: "pip3 --version"
     register: pip_version_output
     ignore_errors: yes

   - name: "Installing pip3 if not found (for Debian/Ubuntu)."
     apt:
        name: python3-pip
        state: present
     when: "not pip_version_output.stdout and ansible_facts['os_family'] == 'Debian'"

   - name: "Installing pip3 if not found (for RedHat/CentOS)."
     yum:
        name: python3-pip
        state: present
     when: "not pip_version_output.stdout and ansible_facts['os_family'] == 'RedHat'"

   - name: "Installing <plugin_name>_Driver Python3 Package."
     pip:
        name: <plugin_name>_Driver
        state: present
        executable: pip3
     ignore_errors: yes

   - name: "Site24x7 Agent Directory Check."
     stat:
      path: "/opt/site24x7/monagent/temp"
     register: agent_path_check

   - name: "Hosts with no Site24x7 Agent Directory"
     debug:
      msg: "Agent Directory not found"
     when: not agent_path_check.stat.exists


   - name: "Site24x7 Temp Plugins Directory Creation."
     file:
      path: "/opt/site24x7/monagent/temp/plugins/<plugin_name>"
      state: directory
     when: agent_path_check.stat.exists

   - name: "Site24x7 Plugin Directory Check"
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/<plugin_name>"
     register: plugin_path_check

   - name: "Download the Site24x7 <plugin_name> Plugin Files."
     get_url:
        url: "{{ item }}"
        dest: "/opt/site24x7/monagent/temp/plugins/<plugin_name>"
        mode: 0744
     loop: ["https://raw.githubusercontent.com/site24x7/plugins/master/<plugin_name>/<plugin_name>.py","https://raw.githubusercontent.com/site24x7/plugins/master/<plugin_name>/<plugin_name>.cfg"]
     when: plugin_path_check.stat.exists
    

  # Site24x7 <plugin_name> Plugin Config File Setup

   - name: "Site24x7 <plugin_name> Config File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/<plugin_name>/<plugin_name>.cfg"
     register: <plugin_name>_file_check

   - name: "Site24x7 <plugin_name> configuration."
     lineinfile: 
       path: "/opt/site24x7/monagent/temp/plugins/<plugin_name>/<plugin_name>.cfg"
       regexp: "{{ item.regex }}"
       line: "{{ item.line }}"
     loop:
       - { regex: 'host =', line: 'host ={{<plugin_name>_host}}' }
       - { regex: 'port =', line: 'port ={{<plugin_name>_port}}' }
       - { regex: 'username =', line: 'username ={{<plugin_name>_username}}' }
       - { regex: 'password =', line: 'password ={{<plugin_name>_password}}' }

     when: <plugin_name>_file_check.stat.exists


  # Site24x7 <plugin_name> Python File Setup

   - name: "Site24x7 <plugin_name> Python File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/<plugin_name>/<plugin_name>.py"
     register: <plugin_name>_python_file_check

   - name: "Extracting Python3 Default Path."
     command: which python3
     register: python3_path

   - set_fact:
      actual_path: "{{ '#!'+python3_path.stdout }}"

   - name: "Setting the Default Python Path for the Site24x7 <plugin_name> Plugin"
     lineinfile:
       path: "/opt/site24x7/monagent/temp/plugins/<plugin_name>/<plugin_name>.py"
       regexp: "#!"
       line: "{{actual_path}}"
     when: <plugin_name>_python_file_check.stat.exists

   - name: "Checking the Site24x7 <plugin_name> Plugin Output"
     shell: "python3 /opt/site24x7/monagent/temp/plugins/<plugin_name>/<plugin_name>.py --host={{<plugin_name>_host}} --port={{<plugin_name>_port}} --username={{<plugin_name>_username}} --password={{<plugin_name>_password}}"
     register: <plugin_name>_python_output
     when: <plugin_name>_python_file_check.stat.exists

   - name: "Site24x7 <plugin_name> plugins with Error !"
     debug:
      msg: "Site24x7 <plugin_name> Plugin OUTPUT error ! \n {{ <plugin_name>_python_output.stdout }}"
     when: "'\"status\": 0' in <plugin_name>_python_output.stdout and <plugin_name>_python_file_check.stat.exists"

   - name: "Moving the Site24x7 <plugin_name> Folder to the Plugins Directory"
     command: "mv  /opt/site24x7/monagent/temp/plugins/<plugin_name> /opt/site24x7/monagent/plugins"
     ignore_errors: true
     when: "plugin_path_check.stat.exists and '\"status\": 0' not in <plugin_name>_python_output.stdout"
